name: Scheduled Python Script

on:
  schedule:
    - cron: '0 2 * * 1'  # Runs at 2 AM every Monday
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python script.py
